# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sample.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SampleView(object):
    def setupUi(self, SampleView):
        SampleView.setObjectName("SampleView")
        SampleView.resize(403, 305)
        self.layoutWidget = QtWidgets.QWidget(SampleView)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 371, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_version = QtWidgets.QLabel(self.layoutWidget)
        self.label_version.setObjectName("label_version")
        self.gridLayout.addWidget(self.label_version, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 2)

        self.retranslateUi(SampleView)
        self.pushButton.pressed.connect(SampleView.show_random)
        QtCore.QMetaObject.connectSlotsByName(SampleView)

    def retranslateUi(self, SampleView):
        _translate = QtCore.QCoreApplication.translate
        SampleView.setWindowTitle(_translate("SampleView", "Form"))
        self.label.setText(_translate("SampleView", "当前版本号："))
        self.label_version.setText(_translate("SampleView", "TextLabel"))
        self.pushButton.setText(_translate("SampleView", "弹窗"))
