image: 192.168.16.36:5000/cicd

variables: 
  PYTHON: python{{ cookiecutter.python_version }}

stages:
  - lint
  - test
  - build
  - deploy

lint:
  before_script:
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
    - $PYTHON -m pip install -U pip
    - $PYTHON -m pip install -e . -f 3rdparty
  stage: lint
  script:
    - $PYTHON -m pre_commit run -a
    - $PYTHON -m tox -e gitlint -- --commits HEAD
  tags:
    - docker
    - local

test:
  stage: test
  script:
    - $PYTHON -m tox
  tags:
    - docker
    - local

build_repo:
  stage: build
  before_script:
    - $PYTHON -m pip install -U pip
    - $PYTHON -m pip install -e . -f 3rdparty
  script:
    - $PYTHON -m invoke freeze
  artifacts:
    paths:
      - dist
    expire_in: 3 day
  tags:
    - docker
    - local
  only:
    - tags

deploy:
  stage: deploy
  variables:
    URL: "http://192.168.16.35:5001/upload/{{ cookiecutter.project_slug }}"
  before_script:
    - $PYTHON -m pip install -U pip
    - $PYTHON -m pip install -e . -f 3rdparty
  script:
    - $PYTHON -m invoke upload -f dist/{{ cookiecutter.project_slug }} -u $URL
  dependencies:
    - build_repo
  tags:
      - docker
      - local
  only:
    - tags
