image: 192.168.16.36:5000/cicd

stages:
  - lint
  - test
  - build
  - deploy

lint:
  before_script:
    - pyenv local 3.7.6
    - python -V
    - export LC_ALL=C.UTF-8
    - export LANG=C.UTF-8
  stage: lint
  script:
    - pip install -U pip
    - pip install -e . -f 3rdparty
    - pre-commit run -a
    - gitlint --commits HEAD
  tags:
    - docker
    - local

test:
  before_script:
    - pyenv local 3.7.6
    - python -V
  stage: test
  script:
    - pip install -U pip
    - pip install -e . -f 3rdparty
    - inv test
  tags:
    - docker
    - local

build_repo:
  stage: build
  before_script:
    - pyenv local 3.7.6
  script:
    - pip install -U pip
    - pip install -e . -f 3rdparty
    - inv freeze
  artifacts:
    paths:
      - dist
    expire_in: 3 day
  tags:
    - docker
    - local
  only:
    - tags

deploy:
  before_script:
    - pyenv local 3.7.6
  stage: deploy
  variables:
    URL: "http://192.168.16.35:5001/upload/{{ cookiecutter.project_slug }}"
  script:
    - pip install -U pip
    - pip install -e . -f 3rdparty
    - inv upload -f dist/{{ cookiecutter.project_slug }} -u $URL
  dependencies:
    - build_repo
  tags:
      - docker
      - local
  only:
    - tags
