# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(437, 283)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_value_1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_value_1.setObjectName("lineEdit_value_1")
        self.gridLayout_2.addWidget(self.lineEdit_value_1, 0, 0, 1, 1)
        self.comboBox_operator = QtWidgets.QComboBox(Form)
        self.comboBox_operator.setObjectName("comboBox_operator")
        self.gridLayout_2.addWidget(self.comboBox_operator, 0, 1, 1, 1)
        self.lineEdit_value_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_value_2.setObjectName("lineEdit_value_2")
        self.gridLayout_2.addWidget(self.lineEdit_value_2, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_result = QtWidgets.QLineEdit(Form)
        self.lineEdit_result.setEnabled(False)
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.gridLayout.addWidget(self.lineEdit_result, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.pushButton_calc = QtWidgets.QPushButton(Form)
        self.pushButton_calc.setObjectName("pushButton_calc")
        self.gridLayout_4.addWidget(self.pushButton_calc, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "="))
        self.pushButton_calc.setText(_translate("Form", "计算"))
